@echo off
echo Running build...
echo Copying the launcher from the NetBeans project...
copy OpenTerraria.Launcher\dist\OpenTerraria.Launcher.jar OpenTerraria\bin\Debug\Launcher.jar
copy OpenTerraria.Launcher\dist\org.eclipse.egit.github.core-2.1.5.jar OpenTerraria\bin\Debug\
echo Creating update zip...
echo Say Yes to the prompt
del Bin\*
echo Deleting unneccisary files...
del OpenTerraria\bin\Debug\save.bin
echo Copying files...
xcopy OpenTerraria\bin\Debug Bin
xcopy OpenTerraria\bin\Debug\images Bin\images
echo Cd-ing to Bin...
cd Bin
echo Adding the commit text file...
echo %1 > commit.txt
echo Zipping it up...
..\7za a updatezip.zip *
echo Cd-ing up one level...
cd ..
echo Copying zip to this directory
del updatezip.zip
copy Bin\updatezip.zip .
echo Git stuff...
git add -A
git commit -m %1
echo You will be prompted for your username and password.
git push -u origin master